import type { LocationContext } from './actions';
import type { InspectResult, RankedAction } from '../types';
import { CPCB_STANDARDS, POLLUTANT_META, bandByKey } from './aqi';
import { formatDateLongIST, formatIN, windDirectionLabel } from './format';

/**
 * Plain-language presentation layer over the rule engine. Deterministic
 * templates stand in for the LLM in mock mode — the same contract applies:
 * only the fired rules and provided context are used, nothing is invented.
 */

export function buildExplanation(ctx: LocationContext): string {
  const parts: string[] = [];
  const top = Object.entries(ctx.sourceShares).sort((a, b) => b[1] - a[1])[0];
  const dir = windDirectionLabel(ctx.windDirectionDegForText ?? 0);

  if (top[0] === 'industrial') {
    parts.push(
      `Wind is carrying emissions from the industrial cluster ${dir ? `${dir.toLowerCase() === 'n' ? 'north' : dir} of here` : 'upwind'} at ${ctx.windSpeedKmh.toFixed(0)} km/h`,
    );
  } else if (top[0] === 'biomass') {
    parts.push(
      `${ctx.firesWithin100km} satellite-detected fires upwind are the largest contributor, carried in on a ${ctx.windSpeedKmh.toFixed(0)} km/h wind`,
    );
  } else if (top[0] === 'traffic') {
    parts.push(
      `Vehicular emissions dominate here, with congestion at ${(ctx.congestionRatio * 100).toFixed(0)}% of free-flow speed on the nearby corridors`,
    );
  } else if (top[0] === 'dust') {
    parts.push(`Road and construction dust dominates, with ${ctx.constructionSitesNearby} active sites nearby`);
  } else {
    parts.push('A mix of area sources dominates at this location');
  }

  if (ctx.boundaryLayerHeightM < 600) {
    parts.push(
      `and a shallow ${ctx.boundaryLayerHeightM.toFixed(0)} m boundary layer is preventing dispersion`,
    );
  } else if (ctx.windSpeedKmh < 6) {
    parts.push(`and near-calm winds (${ctx.windSpeedKmh.toFixed(0)} km/h) are letting pollutants accumulate`);
  }

  let s = parts.join(', ') + '.';
  if (ctx.forecastCrossesBand) {
    s += ` Conditions are expected to worsen — the forecast crosses into ${bandByKey(ctx.forecastCrossesBand.band).label} in about ${ctx.forecastCrossesBand.offsetHours} hours.`;
  } else {
    s += ' No band deterioration is forecast in the next 72 hours.';
  }
  return s;
}

export function buildOrderDraft(action: RankedAction, inspect: InspectResult, placeName: string): string {
  const today = formatDateLongIST(new Date());
  const aq = inspect.airQuality;
  const exceedances = aq.pollutants
    .filter((p) => p.exceeds)
    .map(
      (p) =>
        `${POLLUTANT_META[p.key].label} at ${p.value.toFixed(1)} ${p.unit} (${p.ratio.toFixed(1)}× the ${POLLUTANT_META[p.key].standardNote} standard of ${CPCB_STANDARDS[p.key]} ${p.unit})`,
    )
    .join('; ');

  return `DRAFT DIRECTIVE — FOR REVIEW AND ISSUE

No. VAYU/${new Date().getFullYear()}/${action.id.toUpperCase()}
Date: ${today}

To: ${action.agency}
Subject: ${action.action}

WHEREAS ambient air quality monitoring at ${inspect.location.name} (${inspect.location.lat.toFixed(4)}, ${inspect.location.lon.toFixed(4)}) in ${placeName} records an Air Quality Index of ${aq.aqi} (${bandByKey(aq.band).label}), with ${exceedances || 'no individual pollutant exceedance'};

WHEREAS the operational forecast indicates ${
    inspect.forecast.crossesBandAt
      ? `deterioration into the ${bandByKey(inspect.forecast.crossesBandAt.band).label} category within ${inspect.forecast.crossesBandAt.offsetHours} hours`
      : 'sustained levels over the next 72 hours'
  };

WHEREAS an estimated ${formatIN(inspect.exposure.populationWithin2km)} persons reside within 2 km of the affected location, including ${inspect.exposure.schools} schools and ${inspect.exposure.hospitals} hospitals;

AND WHEREAS the source assessment attributes the exceedance principally to ${inspect.attribution.sources
    .slice(0, 2)
    .map((s) => `${s.label.toLowerCase()} sources (${s.sharePct}%)`)
    .join(' and ')} (assessment confidence ${(inspect.attribution.confidence * 100).toFixed(0)}%);

NOW THEREFORE, in exercise of the powers conferred under ${action.legalBasis}, the following direction is issued:

${action.action}.

Rationale: ${action.reasoning}

Expected effect: a reduction of ${Math.abs(action.estimatedEffect.aqiDelta[1])}–${Math.abs(action.estimatedEffect.aqiDelta[0])} AQI points within ${action.estimatedEffect.withinHours} hours of implementation, subject to meteorological conditions.

Compliance shall be reported within 48 hours of issue.

(Generated by VAYU decision support — figures as observed at generation time. This draft requires review and authorised signature before issue.)`;
}

const ADVISORY_TEMPLATES: Record<string, { title: string; body: (aqi: number, band: string) => string }> = {
  hi: {
    title: 'वायु गुणवत्ता परामर्श',
    body: (aqi, band) =>
      `इस क्षेत्र में वायु गुणवत्ता सूचकांक ${aqi} (${band}) है। संवेदनशील समूह — बच्चे, बुज़ुर्ग और श्वास रोगी — बाहरी गतिविधि सीमित करें। खिड़कियाँ बंद रखें और N95 मास्क का उपयोग करें।`,
  },
  mr: {
    title: 'हवा गुणवत्ता सूचना',
    body: (aqi, band) =>
      `या भागातील हवा गुणवत्ता निर्देशांक ${aqi} (${band}) आहे. संवेदनशील गट — लहान मुले, वृद्ध व श्वसनरुग्ण — बाहेरील हालचाली मर्यादित ठेवा. खिडक्या बंद ठेवा व N95 मास्क वापरा.`,
  },
  bn: {
    title: 'বায়ু মান সতর্কতা',
    body: (aqi, band) =>
      `এই এলাকার বায়ু মান সূচক ${aqi} (${band})। সংবেদনশীল ব্যক্তিরা — শিশু, বয়স্ক ও শ্বাসকষ্টের রোগীরা — বাইরের কার্যকলাপ সীমিত রাখুন। জানালা বন্ধ রাখুন এবং N95 মাস্ক ব্যবহার করুন।`,
  },
  ta: {
    title: 'காற்றுத் தர அறிவுரை',
    body: (aqi, band) =>
      `இப்பகுதியின் காற்றுத் தர குறியீடு ${aqi} (${band}). உணர்திறன் கொண்டவர்கள் — குழந்தைகள், முதியவர்கள், சுவாச நோயாளிகள் — வெளிப்புற செயல்பாடுகளைக் குறைக்கவும். ஜன்னல்களை மூடி வைக்கவும்; N95 முகக்கவசம் பயன்படுத்தவும்.`,
  },
  kn: {
    title: 'ವಾಯು ಗುಣಮಟ್ಟ ಸಲಹೆ',
    body: (aqi, band) =>
      `ಈ ಪ್ರದೇಶದ ವಾಯು ಗುಣಮಟ್ಟ ಸೂಚ್ಯಂಕ ${aqi} (${band}). ಸೂಕ್ಷ್ಮ ಗುಂಪುಗಳು — ಮಕ್ಕಳು, ವೃದ್ಧರು, ಉಸಿರಾಟದ ರೋಗಿಗಳು — ಹೊರಾಂಗಣ ಚಟುವಟಿಕೆ ಮಿತಿಗೊಳಿಸಿ. ಕಿಟಕಿಗಳನ್ನು ಮುಚ್ಚಿಡಿ; N95 ಮಾಸ್ಕ್ ಬಳಸಿ.`,
  },
  en: {
    title: 'Air quality advisory',
    body: (aqi, band) =>
      `The Air Quality Index in this area is ${aqi} (${band}). Sensitive groups — children, the elderly, and those with respiratory conditions — should limit outdoor activity. Keep windows closed and use an N95 mask outdoors.`,
  },
};

export const STATE_LANGUAGE: Record<string, string> = {
  Delhi: 'hi',
  'Uttar Pradesh': 'hi',
  Haryana: 'hi',
  Rajasthan: 'hi',
  'Madhya Pradesh': 'hi',
  Bihar: 'hi',
  Maharashtra: 'mr',
  'West Bengal': 'bn',
  'Tamil Nadu': 'ta',
  Karnataka: 'kn',
};

export function buildAdvisory(aqi: number, bandLabel: string, language: string) {
  const t = ADVISORY_TEMPLATES[language] ?? ADVISORY_TEMPLATES.en;
  return { title: t.title, body: t.body(aqi, bandLabel), language };
}
